include ../include.mk

ifeq ($(TYPE),debug)
DEBUG_FLAGS = -Ddebug
else
DEBUG_FLAGS =
endif

MODULES=serial

EBIN_FILES=$(MODULES:%=../ebin/%.$(EMULATOR))

ERLC_FLAGS+=-W +debug_info $(DEBUG_FLAGS)

#
# Targets
#

all: $(EBIN_FILES)

debug:
	$(MAKE) TYPE=debug

clean:
	rm -f $(EBIN_FILES)
